trigger: none
pr: none
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client-patch.yml
  parameters:
    artifacts:
    - name: azure-messaging-eventhubs-checkpointstore-blob
      groupId: com.azure
      safeName: azuremessagingeventhubscheckpointstoreblob
      ServiceDirectory: eventhubs

